### ISSUE TITLE
Required redirect_uris is optional in GUI

### ISSUE THREAD

**Issue by SamuelLundmark** [gsuitedevs/go-samples#17]
## Expected Behavior
In `Step 4: Run the sample`.
The credentials provided in the `credentials.json` file is correct according to the structs. And I get the message `Go to the following link in your browser then type the authorization code:`

## Actual Behavior
In `Step 4: Run the sample`.
I run the project and get 
```
$ go run quickstart.go
2018/11/10 23:01:12 Unable to parse client secret file to config: oauth2/google: missing redirect URL in the client_credentials.json
exit status 1
```
The parameter `redirect_uris` is required in the code but it is optional in the GUI. 

## Steps to Reproduce the Problem

1. Copy the code into a go file.
1. Run the code `go run quickstart.go` and get 
```
2018/11/10 22:56:52 Unable to read client secret file: open credentials.json: no such file or directory
exit status 1
```
1. Log into my google account and create a project without `Authorized redirect URIs` and `Authorized JavaScript origins`
1. Download the json file.
1. Move the json file next to `quickstart.go`
1. Rename the file to `credentials.json`
1. Run the code again `go run quickstart.go`
1. I get ```2018/11/10 23:01:12 Unable to parse client secret file to config: oauth2/google: missing redirect URL in the client_credentials.json
exit status 1```
1. I then look into the json file `less credentials.json`. The parameters existing under `web` are `client_id`, `project_id`, `auth_uri`, `token_uri`, `auth_provider_x509_cert_url` and `client_secret`. No `redirect_uris` exists.

## Specifications

- Go version (`go version go1.11 darwin/amd64`)
- OS (OSX 10.14.1)

**Comment by erickoledadevrel** [comment]
These quickstarts (I'm not sure which one you are using) assume you are using an OAuth Client ID of type "Other", which includes the redirect URIs `urn:ietf:wg:oauth:2.0:oob` and `oob`. The button in the [Quickstart instructions](https://developers.google.com/calendar/quickstart/go#step_1_turn_on_the) ensures that that the correct client ID type is created.

More generally, the authorization code flow will only work if the correct redirect URI is configured. It's optional in the UI since you don't need to use that flow, for example if using the client-side JavaScript client.
