### ISSUE TITLE
Credentials problem

### ISSUE THREAD

**Issue by proyb6** [gsuitedevs/go-samples#39]
The Go documentation is incomplete and need help urgently on the step to create new credentials.json which it has additional missing key but I tried to generate a private JSON in Google API console is confusing that I'm stuck with no proper guidance.
https://developers.google.com/sheets/api/quickstart/go?authuser=2

Someone has changed the credential requirements without inform anyone and create all the mess.

Go code for Sheetv4 is running on web server.

**Comment by ololosha228** [comment]
Holy moly, this issue didn't answered whole 2 weeks? @henry-jackson see you commited some examples, may be you can help?

**Comment by sqrrrl** [comment]
The issue appears to be related to having multiple accounts logged in and trying to use that button with the non-primary account (the presence of the ?authuser=2 query parameter.)

You can work around it by either using your primary account or creating a new user profile for the other account and log in as the primary one there. I ran through the quickstart using a primary account and was able to complete it successfully.

I did file a bug for the multi-account issue, but that'll take some time to get fixed.

In the future, please try to file more constructive issues. There's very little explanation of the actual error (to the contrary, it's quite misleading,) no screenshot or attempt to debug or isolate the issue.

Anyway, since the sample itself is fine and the login issue will be tracked elsewhere, closing this one.
